### ISSUE TITLE
[Feature Request] Separate branch for LTS202407.00 release and 202210.01-LTS

### ISSUE THREAD

**Issue by NightSkySK** [FreeRTOS/iot-reference-esp32#101]
Can we have a separate branch to trace changes applied based on 202210.01 LTS and a separate one for the new LTS202407 release?

Some users (including myself) don't want yet to transfer to the new LTS release and searching through commits which is for the new LTS which is related to the previose one is tricky.

Please consider keeping similar split as [esp-aws-iot repo](https://github.com/espressif/esp-aws-iot) 

![image](https://github.com/user-attachments/assets/4adc7147-a0af-49a8-b328-392407ee2ab2)

Than if any new commit might be applied to previose  202210.01 LTS easier

**Comment by kstribrnAmzn** [comment]
Thanks for the suggestion. For now, we'll keep using our existing tag strategy. If we do end up applying a patch to our older (202210.01) LTS release we will consider using this strategy.

**Comment by NightSkySK** [comment]
The last release was published in Dec 2022. 
![image](https://github.com/user-attachments/assets/df29a4f1-76b7-4934-8f63-ba0ba729b132)
Since then hundreds of commits were published which were still applicable to (202210.01) LTS 
![image](https://github.com/user-attachments/assets/71b0c5ef-b5e8-440f-b123-62d41d352a99)

And now since one month you've started to move into LTS202407.00, there is no clear borderline between those events. That's why I wish to have a separate branch.

**Comment by ActoryOu** [comment]
Hi @NightSkySK,
IMHO, either stay in old tag or using new tag is fine. It's not recommended to cherry pick commits back to the old tag unless you know what you're doing.
If there is any critical issue using old tag, please let us know.

Thank you.

**Comment by ActoryOu** [comment]
Closing the issue as there are no further questions for now.
